name = "yoitapbot"
main = "api/worker.js"
compatibility_date = "2024-06-02"
[vars]
BOT_TOKEN = "7755936373:AAGpeQ7Arxee288t4HhXwfs15wtWOkZNHmI"
BOT_USERNAME = "yoitapbot"
EMOJI_LIST = "ğŸ‘â¤ğŸ”¥ğŸ¥°ğŸ‘ğŸ˜ğŸ‰ğŸ¤©ğŸ™ğŸ‘ŒğŸ•ŠğŸ˜ğŸ³â¤â€ğŸ”¥ğŸ’¯âš¡ğŸ†"
RANDOM_LEVEL = "2"
RESTRICTED_CHATS = "1234,5678"
